# Generated by Django 3.2 on 2021-04-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product')),
                ('product_price', models.FloatField(verbose_name='Price')),
                ('discount_price', models.FloatField(verbose_name='Discount Price')),
                ('category', models.CharField(max_length=200, verbose_name='Category')),
                ('product_description', models.TextField(verbose_name='Description')),
                ('product_image', models.CharField(max_length=500, verbose_name='Image')),
                ('prdocut_sku', models.CharField(max_length=100, verbose_name='SKU')),
                ('product_availability', models.BooleanField(verbose_name='In Stock')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
