# Generated by Django 3.2 on 2021-04-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='¿Has Discount?'),
        ),
    ]
