# Generated by Django 3.2 on 2021-05-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=1000, verbose_name='Items Ordered')),
                ('name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Customer Last Name')),
                ('email', models.CharField(max_length=200, verbose_name='Customer Email')),
                ('address', models.CharField(max_length=200, verbose_name='Customer Address')),
                ('address2', models.CharField(max_length=200, verbose_name='Customer Apartment')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('state', models.CharField(max_length=200, verbose_name='State')),
                ('zip_code', models.CharField(max_length=200, verbose_name='Zip Code')),
                ('billing_shipping', models.BooleanField(verbose_name='Billing Address equals Shipping Address?')),
                ('save_info', models.BooleanField(verbose_name='Save Customer Information?')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
