# Generated by Django 3.2 on 2021-05-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='billing_shipping',
            field=models.BooleanField(default=False, verbose_name='Billing Address equals Shipping Address?'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='save_info',
            field=models.BooleanField(default=False, verbose_name='Save Customer Information?'),
        ),
    ]
