# Generated by Django 3.2 on 2021-05-03 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210502_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='billing_shipping',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='save_info',
        ),
    ]
