# Generated by Django 3.2 on 2021-05-03 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210502_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ('id', 'name', 'last_name'), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
