# Generated by Django 3.2 on 2021-05-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_ordermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='total',
            field=models.FloatField(default=0, max_length=200, verbose_name='Order Total'),
        ),
    ]
